### ISSUE TITLE
Subdomains for campaigns

### ISSUE THREAD

**Issue by apaleslimghost** [apaleslimghost/almanac#84]
- [ ] allow setting custom slug
  - [ ] check it's unique
  - [ ] check it's not something like `staging` that would collide with another subdomain or `login` that would collide with another path
  - [ ] does this actually set the doc id as with the current `generateSlug` or is it another field to look up by
- [ ] set up wildcard DNS (namecheap)
- [ ] set up heroku domain routing
- [ ] how would this hook into the router?

**Comment by apaleslimghost** [comment]
😕 currently heroku automated certificate management isn't compatible with wildcard domains https://help.heroku.com/EUV5TCYK/why-doesn-t-automated-certificate-management-support-wildcard-domains

**Comment by apaleslimghost** [comment]
closing as not feasible for now
